# Generated by Django 5.2 on 2025-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_car_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
    ]
