# Generated by Django 5.2 on 2025-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
